# Generated by Django 2.0.5 on 2018-05-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('a_paterno', models.CharField(max_length=50)),
                ('a_materno', models.CharField(max_length=50)),
                ('distrito', models.IntegerField()),
                ('clave_resp', models.IntegerField()),
                ('password', models.CharField(max_length=12)),
                ('puesto', models.IntegerField()),
                ('sexo', models.IntegerField()),
            ],
        ),
    ]
