# Generated by Django 2.0.5 on 2018-05-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_sexo', models.IntegerField()),
                ('sexo', models.CharField(max_length=1)),
            ],
        ),
    ]
