# Generated by Django 2.0.5 on 2018-05-16 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0002_sexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sexo',
            name='id',
        ),
        migrations.AlterField(
            model_name='persona',
            name='clave_resp',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='persona',
            name='sexo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personal.Sexo'),
        ),
        migrations.AlterField(
            model_name='sexo',
            name='clave_sexo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
