# Generated by Django 2.0.5 on 2018-05-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0003_auto_20180516_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='sexo',
            field=models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], default='H', max_length=1),
        ),
        migrations.DeleteModel(
            name='Sexo',
        ),
    ]
