# Generated by Django 2.0.5 on 2018-05-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0004_auto_20180516_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='distrito',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)]),
        ),
        migrations.AlterField(
            model_name='persona',
            name='sexo',
            field=models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1),
        ),
    ]
