# Generated by Django 2.0.5 on 2018-05-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0005_auto_20180516_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='sexo',
            field=models.CharField(choices=[('Hombre', 'H'), ('Mujer', 'M')], max_length=1),
        ),
    ]
