# Generated by Django 2.0.5 on 2018-05-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0007_auto_20180516_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='clave_resp',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
