# Generated by Django 2.0.5 on 2018-05-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0008_auto_20180516_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='sexo',
            field=models.CharField(choices=[('Hombre', 'H'), ('Mujer', 'M')], max_length=2),
        ),
    ]
